# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: keios.support::lang.ticketcreator.label

# Model Form Field configuration
form: $/keios/support/models/ticketcreator/fields.yaml

# Model Class name
modelClass: Keios\Support\Models\TicketCreator

# Default redirect location
defaultRedirect: keios/support/ticketcreators

# Create page
create:
    title: keios.support::lang.ticketcreator.create_title
    redirect: keios/support/ticketcreators/update/:id
    redirectClose: keios/support/ticketcreators

# Update page
update:
    title: keios.support::lang.ticketcreator.update_title
    redirect: keios/support/ticketcreators
    redirectClose: keios/support/ticketcreators

# Preview page
preview:
    title: keios.support::lang.ticketcreator.preview_title